dist: bionic
addons:
  apt:
    sources:
      - chef-stable-bionic
    packages:
      - chef-workstation

env:
  - CHEF_LICENSE=accept

services:
  - docker

env:
  matrix:
    - INSTANCE=default-amazonlinux-2
    - INSTANCE=default-debian-10
    - INSTANCE=default-ubuntu-1804
    - INSTANCE=default-ubuntu-2004
    - INSTANCE=default-ubuntu-1804 CHEF_VERSION=13
    - INSTANCE=default-ubuntu-1804 CHEF_VERSION=14

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - export CHEF_LICENSE=accept
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
        - delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
